---
- hosts: gateway
  remote_user: ansible
  become: true
  become_method: sudo
  tasks:
  - include_vars: accounts.yml
  - name: Add user and set password
    user:
      name: "{{ item.novalue }}"
      password: "{{ item.password | password_hash('md5') }}"
      update_password: on_create
      shell: /bin/bash 
    with_items: "{{ users }}"
